service:
  message: welcome , my guest

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: uplooking
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: stat.mergeSql=true;stat.slowSqlMillis=5000
    ##useGlobalDataSourceStat: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  devtools:
    restart:
      additional-paths: demo-springboot-application/src/main/java
      exclude: demo-springboot-application/src/main/resources/**

management:
  server:
    port: 9090
  endpoints:
    web:
      cors:
        allow-credentials: false
      exposure:
        include: "*"